# Generated by Django 3.0.8 on 2020-12-01 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default=0, max_length=20)),
                ('lastName', models.CharField(default=0, max_length=20)),
                ('university', models.CharField(default=0, max_length=50)),
                ('email', models.EmailField(default=0, max_length=50)),
                ('mobile', models.CharField(default=0, max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'female'), ('Others', 'others')], max_length=10)),
                ('dob', models.DateField(default=0)),
                ('address', models.CharField(default=0, max_length=50)),
                ('hobby', models.CharField(choices=[('Drawing', 'singing'), ('Swimming', 'swimming'), ('Dancing', 'Dancing'), ('Reading', 'reading')], max_length=20)),
                ('qualifications', models.CharField(choices=[('High School', 'High School'), ('Higher school', 'higher school'), ('Bachelors', 'Bachelors'), ('P.H.D', 'P.H.D')], max_length=30)),
                ('subject', models.CharField(choices=[('Computer Science', 'Computer science'), ('MBA', 'MBA'), ('BBA', 'BBA'), ('civil Engineer', 'CIvil Engineer')], max_length=20)),
                ('applypopularity', models.IntegerField(default=0)),
                ('appliedon', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-applypopularity'],
            },
        ),
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default=0, max_length=10)),
                ('lastName', models.CharField(default=0, max_length=10)),
                ('email', models.EmailField(default=0, max_length=50)),
                ('mobile', models.CharField(default=0, max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'female'), ('Others', 'others')], max_length=20)),
                ('startdate', models.DateField(blank=True, null=True)),
                ('selectclass', models.CharField(choices=[('IELTS', 'IELTS'), ('TOEFL', 'TOEFL'), ('SAT', 'SAT'), ('GRE', 'GRE')], max_length=10)),
                ('bookingpopularity', models.IntegerField(default=0)),
                ('shift', models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening')], max_length=20)),
                ('payment', models.CharField(choices=[('SKrill', 'Skrill'), ('PAypal', 'Paypal'), ('e-sewa', 'esewa')], max_length=20)),
                ('recipt', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'ordering': ['-bookingpopularity'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postTitle', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('postImage', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('country', models.CharField(max_length=45)),
                ('updatedOn', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-postTitle'],
            },
        ),
        migrations.CreateModel(
            name='postReactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.IntegerField()),
                ('postId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='axisPosts.Post')),
                ('userName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='postComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('comment', models.TextField()),
                ('popularity', models.IntegerField(default=0)),
                ('updatedOn', models.DateTimeField(auto_now=True)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('commentAuthor', models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
                ('parentId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='axisPosts.postComments')),
                ('postId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='axisPosts.Post')),
            ],
            options={
                'ordering': ['-popularity'],
            },
        ),
        migrations.CreateModel(
            name='commentReactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.IntegerField()),
                ('commentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='axisPosts.postComments')),
                ('userName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
