# Generated by Django 3.0.8 on 2020-11-27 04:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default=0, max_length=10)),
                ('lastName', models.CharField(default=0, max_length=10)),
                ('email', models.CharField(default=0, max_length=10)),
                ('mobile', models.IntegerField(default=0)),
                ('gender', models.CharField(default=0, max_length=10)),
                ('dob', models.DateField(default=0)),
                ('address', models.CharField(default=0, max_length=50)),
                ('hobby', models.CharField(default=0, max_length=10)),
                ('qualifications', models.CharField(default=0, max_length=10)),
                ('subject', models.CharField(default=0, max_length=10)),
                ('applypopularity', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-applypopularity'],
            },
        ),
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default=0, max_length=10)),
                ('lastName', models.CharField(default=0, max_length=10)),
                ('email', models.CharField(default=0, max_length=10)),
                ('mobile', models.IntegerField(default=0)),
                ('gender', models.CharField(default=0, max_length=10)),
                ('startdate', models.DateField(default=0)),
                ('selectclass', models.CharField(default=0, max_length=10)),
                ('bookingpopularity', models.IntegerField(default=0)),
                ('shift', models.CharField(default=0, max_length=10)),
                ('recipt', models.ImageField(default=0, upload_to='images/')),
            ],
            options={
                'ordering': ['-bookingpopularity'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postTitle', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('postImage', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('country', models.CharField(max_length=50)),
                ('updatedOn', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-postTitle'],
            },
        ),
        migrations.CreateModel(
            name='postReactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.IntegerField()),
                ('postId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='axisPosts.Post')),
                ('userName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='postComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('comment', models.TextField()),
                ('popularity', models.IntegerField(default=0)),
                ('updatedOn', models.DateTimeField(auto_now=True)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('commentAuthor', models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
                ('parentId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='axisPosts.postComments')),
                ('postId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='axisPosts.Post')),
            ],
            options={
                'ordering': ['-popularity'],
            },
        ),
        migrations.CreateModel(
            name='commentReactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.IntegerField()),
                ('commentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='axisPosts.postComments')),
                ('userName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
