# Generated by Django 3.1 on 2020-11-29 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('axisPosts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apply',
            old_name='firstname',
            new_name='firstName',
        ),
    ]
