# Generated by Django 3.0.8 on 2020-12-09 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axisPosts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='appliedon',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
