# Generated by Django 3.0.8 on 2020-11-30 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('axisPosts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='firstName',
            new_name='firstname',
        ),
    ]
