# Generated by Django 3.1 on 2020-11-24 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axisPosts', '0002_auto_20201124_0650'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingpopularity', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-bookingpopularity'],
            },
        ),
    ]
