# Generated by Django 3.0.8 on 2020-11-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axisPosts', '0003_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='updatedOn',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
