# Generated by Django 3.0.8 on 2020-11-29 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axisPosts', '0003_auto_20201130_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='university',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
