# Generated by Django 3.0.8 on 2020-11-29 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axisPosts', '0004_apply_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='appliedon',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
