# Generated by Django 3.0.8 on 2020-11-26 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axisPosts', '0004_post_updatedon'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='poster',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
