# Generated by Django 3.0.8 on 2020-11-26 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axisPosts', '0005_post_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='poster',
            field=models.CharField(max_length=20),
        ),
    ]
