# Generated by Django 3.0.8 on 2020-11-26 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('axisPosts', '0006_auto_20201127_0849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='poster',
        ),
    ]
